### ISSUE TITLE
Adding journal by pop-up window

### ISSUE THREAD

**Issue by Aaron3963** [cse110-sp24-group22/cse110-sp24-group22#18]
Use the `modal` which Ethan mentions, create the `editJournal` function / feature which will behave like the following:

- Triggered when clicked
- Display a pop-up window on top of the webpage, containing
  - The Title entry bar
  - The timestamp (rename it when display) (not-editable)
  - The tag bar
    - Thinking of having a [Tag:] container, followed by a "+" button to add tag
  - The Quill editor
    - Tool bar
    - Text box
  - Delete button
  - Save button

On functionality wise:

- Store title when the bar content changes
- Store / delete tag
- Store changes to the text editor

Things still need to think about:
- How to implement the delete tag feature

**Comment by EdgarNonsense** [comment]
um it's modal not model
