### ISSUE TITLE
[Feature] Update list view page to follow the design in Figma

### ISSUE THREAD

**Issue by warren231** [cse110-sp24-group22/cse110-sp24-group22#21]
# Update list view page to follow the design in Figma

## Short descirption
Right now the list view design is pretty different from that on [Figma](https://www.figma.com/design/jI9imcuPdGE3AL2bU9qolt/Project-Workfllow?node-id=0-1), but it should follow the mockups.

## Assignees
  (using @cse110-sp24-group22/[teamname]) or names

## Feature's checkpoints
- [x] Move New Journal button to always be on bottom right
- [x] Change element colors and sizing
- [x] Make the layout of entries tabular like in Figma
- [x] Add delete confirmation pop-up
- [x] Implement the search/logo/other buttons header
- [x] #57 

## ETA
Seems like a medium task, perhaps 2+ hours

## Note
**Do not forget** to assign your group on the right, as well as link the corresponding branch/PR with it.

**Comment by SatvikS7** [comment]
![image](https://github.com/cse110-sp24-group22/cse110-sp24-group22/assets/79161050/416dd0cd-2848-4b88-9057-5c816f300408)

what list view page looks like as of 5/26

**Comment by jankwong705** [comment]
I'll do delete-confirmation

**Comment by jankwong705** [comment]
![Screenshot 2024-05-28 at 00 14 19](https://github.com/cse110-sp24-group22/cse110-sp24-group22/assets/114449531/f4edd897-f24d-485b-9966-5bd1530b346e)

**Comment by SatvikS7** [comment]
@jankwong705 is it possible to do this within my branch so that it can format with the final look of the list view page

**Comment by jankwong705** [comment]
Yep will do tmr
