### ISSUE TITLE
[Feature] Tag inputs

### ISSUE THREAD

**Issue by Aaron3963** [cse110-sp24-group22/cse110-sp24-group22#24]
## Short discrption
Able to edit tags while the editor is open.

## Feature's checkpoints
- [x] Edit tags.
- [x] Delete tags.

## ETA
Should be around 1 hour.

## Note
**Do not forget** to assign your group on the right, as well as link the corresponding branch/PR with it.

**Comment by jankwong705** [comment]
- can add/change/delete unique tags to each journal
- tags are saved globally 
- tags added will be displayed as buttons 
- clicking on each tag button will prompt user to delete the tag
- input bar + dropdown menu for adding tags 
- dropdown menu displays globally saved tags 
- any bugs have been fixed
