### ISSUE TITLE
[BUG] list-page modal strange behavior

### ISSUE THREAD

**Issue by Aaron3963** [cse110-sp24-group22/cse110-sp24-group22#25]
**Describe the bug**
When the editor is open, if you click outside the editor, it will close the editor.

**To Reproduce**
1. Hit `new-journal` button or click on eixsting journal.
2. Click outisde the editor box.

**Expected behavior**
Should not do anything when clicking outside the editor. Only save and the close button should exit the editor.

**Screenshots**
If applicable.

**Additional context**

**Comment by jankwong705** [comment]
I think this bug can become a feature. Sometimes people want to exit the window by clicking outside of the box.

**Comment by Aaron3963** [comment]
> I think this bug can become a feature. Sometimes people want to exit the window by clicking outside of the box.

I get what you mean, but this bug is awful because if you want to select text in the editor, when to hold ur mouse and accidentally moved across the boarder, the editor closes :(
