### ISSUE TITLE
[BUG] Empty journal with no title and entry is stored

### ISSUE THREAD

**Issue by Aaron3963** [cse110-sp24-group22/cse110-sp24-group22#31]
**Describe the bug**
As  the title mentions.

**To Reproduce**
 Currently if you create a new journal, do nothing and click close, it will be saved.

**Expected behavior**
Expect it will not be saved, or prompt the user to name it sth.

**Screenshots**
If applicable.

**Additional context**

**Comment by anematode** [comment]
I'll take this one.
